const swords = [
    {
        sid: 1,
        name: "Iron Shortsword",
        price: "$550",
        variants: ["38cm", "52cm", "61cm"],
        image: "https://p3d.in/static/uploads/6190/image-c987122602.png",
        quantity: 0,
        fav: false,
    },
    
    {
        sid: 2,
        name: "Steel Shortsword",
        price: "$350",
        variants: ["38cm", "52cm", "61cm"],
        image: "https://p3d.in/static/uploads/6190/image-7cb8128678.png",
        quantity: 10,
        fav: false,
    },

    {
        sid: 3,
        name: "Iron Longsword",
        price: "$799",
        variants: ["100cm", "115cm", "130cm"],
        image: "https://p3d.in/static/uploads/6190/image-d963122086.png",
        quantity: 10,
        fav: false,
    },

    {
        sid: 4,
        name: "Iron Saber",
        price: "$669",
        variants: ["89cm", "92cm"],
        image: "https://p3d.in/static/uploads/6190/image-236b126702.png",
        quantity: 10,
        fav: false,
    },

    {
        sid: 5,
        name: "Iron Tanto",
        price: "$479",
        variants: ["15cm", "23cm","30cm"],
        image: "https://p3d.in/static/uploads/6190/image-05d8128380.png",
        quantity: 8,
        fav: false,
    },





    {
        sid: 6,
        name: "Katana",
        price: "$550",
        variants: ["60cm", "70cm"],
        image: "https://p3d.in/model_data/snapshot/NfK5s",
        quantity: 4,
        fav: false,
    },
    {
        sid: 7,
        name: "Claymore",
        price: "$1299",
        variants: ["120cm", "130cm","140cm", "mega"],
        image: "https://p3d.in/model_data/snapshot/ZA1m9",
        quantity: 8,
        fav: false,
    },
    {
        sid: 8,
        name: "Master Sword",
        price: "$1 000 000",
        variants: ["90cm"],
        image: "https://p3d.in/model_data/snapshot/do4cd",
        quantity: 1,
        fav: false,
    },
    {
        sid: 9,
        name: "Zweihander",
        price: "$1439",
        variants: ["213cm", "220cm"],
        image: "https://p3d.in/model_data/snapshot/CF4ws",
        quantity: 4,
        fav: false,
    },
    {
        sid: 10,
        name: "Scimitar",
        price: "$499",
        variants: ["76cm", "80cm","85cm", "91cm"],
        image: "https://p3d.in/model_data/snapshot/u40LL",
        quantity: 10,
        fav: false,
    },
    {
        sid: 11,
        name: "AS100 Safety Knife",
        price: "$39",
        variants: ["17cm"],
        image: "https://p3d.in/static/uploads/94259/image-01cf1289105.png",
        quantity: 12,
        fav: false,
    },
    {
        sid: 12,
        name: "Cutlass",
        price: "$199",
        variants: ["60cm", "70cm"],
        image: "https://p3d.in/model_data/snapshot/mpJnI",
        quantity: 5,
        fav: false,
    },
    {
        sid: 13,
        name: "Stone (sword sold separately)",
        price: "$90",
        variants: ["60cm", "90cm","140cm"],
        image: "https://p3d.in/model_data/snapshot/Cyd0o",
        quantity: 60,
        fav: false,
    },
    {
        sid: 14,
        name: "Epée",
        price: "$620",
        variants: ["110cm"],
        image: "https://p3d.in/static/uploads/103037/image-0f321479312.png",
        quantity: 17,
        fav: false,
    },
    {
        sid: 15,
        name: "Cardboard Sword",
        price: "$15",
        variants: ["40cm", "70cm"],
        image: "https://p3d.in/model_data/snapshot/9B1q4",
        quantity: 20,
        fav: false,
    },
];

export default swords;